services:
  web:
    image: ${WEB_NEW_IMAGE}
    container_name: flask-app-web-staging
    restart: always
    ports:
      - "5077:5077"
    env_file:
      - .env
    networks:
      - cloudflare_net

  worker:
    image: ${WORKER_NEW_IMAGE}
    container_name: flask-app-worker-staging
    restart: always
    env_file:
      - .env
    command: ["python", "worker.py"]
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    external: true
