services:
  web:
    image: flask-app-web-staging
    container_name: flask-app-web-staging
    restart: always
    ports:
      - "5077:5000"
    env_file:
      - .env
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    volumes:
      - .:/app
    networks:
      - cloudflare_net

  worker:
    image: flask-app-worker-staging
    container_name: flask-app-worker-staging
    restart: always
    env_file:
      - .env
    command: ["python", "worker.py"]
    volumes:
      - .:/app
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    external: true
